version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: jobsity_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  pgdata: